const AcceleraterData = [
  {
    title: "Intel® Gaudi® AI Accelerators",
    name: "Intel® Gaudi® 2",
    Configuration: "8 accelerators on a Universal Baseboard (UBB)",
    priceINR: 65000,
    Per_unit_Estimate: "Approximately $8,125",
    Availability: "Currently available",
    Performance: "Offers competitive AI training and inference capabilities",
    Form_Factor: "",
    Features: "",
    Specifications: "",
    img_url: "/Acceleraters/a-1.jpeg",
  },
  {
    title: "Intel® Gaudi® AI Accelerators",
    name: "Intel® Gaudi® 2",
    Configuration: "8 accelerators on a UBB",
    priceINR: 125000,
    Per_unit_Estimate: "Approximately $15,650",
    Availability: "Expected to launch in Q3 2024",
    Performance: "",
    Form_Factor: "",
    Features: "",
    Specifications: "",
    img_url: "/Acceleraters/a-2.jpeg",
  },
  {
    title: "Intel® Gaudi® AI Accelerators",
    name: "Intel® Gaudi® HL-205",
    Configuration: "",
    priceINR: 65000,
    Per_unit_Estimate: "Approximately $8,125",
    Availability: "Currently available",
    Performance: "Typically integrated into server systems",
    Form_Factor: "OAM module",
    Features: "",
    Specifications: "",
    img_url: "/Acceleraters/a-3.jpeg",
  },
  {
    title: "Intel® Gaudi® AI Accelerators",
    name: "Intel® Gaudi® HLS-1 AI Training System",
    Configuration: "Server system with 8 Gaudi processors",
    priceINR: 90000,
    Per_unit_Estimate: "Approximately $8,125",
    Availability: "Currently available",
    Performance: "",
    Form_Factor: "",
    Features:
      "Includes networking components and is optimized for scalable AI training",
    Specifications: "",
    img_url: "/Acceleraters/a-4.jpeg",
  },
  {
    title: "Intel® Data Center GPU Flex Series",
    name: "Intel® Data Center GPU Flex Series 140",
    priceINR: 75000,
    Per_unit_Estimate: "Approximately $8,125",
    Availability: null,
    Performance: "Offers competitive AI training and inference capabilities",
    Specifications: "Based on Intel® Xe architecture",
    Features: null,
    Form_Factor: null,
    Configuration: null,
    img_url: "/Acceleraters/a-5.jpeg",
  },
  {
    title: "Intel® Data Center GPU Flex Series",
    name: "Intel® Data Center GPU Flex Series 170",
    priceINR: 60000,
    Per_unit_Estimate: "Approximately $8,125",
    Availability: "Currently available",
    Performance: "Offers competitive AI training and inference capabilities",
    Specifications: "Enhanced compute and memory capabilities over the 140",
    Features: "Target Workloads: Video transcoding and AI inference at scale",
    Form_Factor: null,
    Configuration: null,
    img_url: "/Acceleraters/a-6.jpeg",
  },
  {
    title: "Intel® Data Center GPU Flex Series",
    name: "Intel® Flex Series GPU A770",
    priceINR: 55000,
    Per_unit_Estimate: "Approximately $8,125",
    Availability: null,
    Performance: "Offers competitive AI training and inference capabilities",
    Specifications: "Includes ray tracing support",
    Features: "Target Workloads: Media and AI workloads in data centers",
    Form_Factor: null,
    Configuration: null,
    img_url: "/Acceleraters/a-7.jpeg",
  },
  {
    title: "Intel® Data Center GPU Flex Series",
    name: "Intel® Flex Series GPU Reference Platform",
    priceINR: 40000,
    Per_unit_Estimate: "Approximately $8,125",
    Availability: "Currently available",
    Performance: "Offers competitive AI training and inference capabilities",
    Features: "Purpose: Development and testing platform for evaluating and deploying Flex GPUs",
    Specifications: null,
    Form_Factor: null,
    Configuration: null,
    img_url: "/Acceleraters/a-8.jpeg",
  },
];

module.exports = { data: AcceleraterData };
