const Proccessordata = [
  {
    title: "Intel® Core™ Ultra Processors",
    name: "Intel® Core™ Ultra 9 285K", 
    cores: " 24", 
    maxTurboFrequencyGHz: "5.7 GHz", 
    cacheMB: "36 MB", 
    graphics: "Intel® Graphics", 
    launchDate: "Q4'24", 
    priceINR: "₹45,999",
    img_url : "/proccessors/ic-1.jpeg"
  },
  {
    title: "Intel® Core™ Ultra Processors",
    name: "Intel® Core™ Ultra 7 265K",
    cores: "20",
    maxTurboFrequencyGHz: "5.5 GHz",
    cacheMB: "30 MB",
    graphics: "Intel® Graphics",
    launchDate: "Q4'24",
    priceINR: "₹38,000",
    img_url: "/proccessors/ic-2.jpeg"
  },
  {
    title: "Intel® Core™ Ultra Processors",
    name: "Intel® Core™ Ultra 9 285K",
    cores: "14",
    maxTurboFrequencyGHz: "5.2 GHz",
    cacheMB: "24 MB",
    graphics: "Intel® Graphics",
    launchDate: "Q4'24",
    priceINR: "₹31,450",
    img_url: "/proccessors/ic-3.jpeg"
  },
  {
    title: "Intel® Core™ Ultra Processors",
    name: "Intel® Core™ Ultra 9 285K",
    cores: "8",
    maxTurboFrequencyGHz: "5.0 GHz",
    cacheMB: "12 MB",
    graphics: "Intel® Arc™ 140V",
    launchDate: "Q3'24",
    priceINR: "₹24,299",
    img_url: "/proccessors/ic-4.jpeg"
  },
 
  {
    title: "Intel® Core™ Processors",
    name: "Intel® Core™ i9-13900K",
    cores: "24 (8 Performance-cores, 16 Efficient-cores)",
    maxTurboFrequencyGHz: "5.8 GHz",
    cacheMB: "36 MB",
    graphics: "Intel® UHD Graphics 770",
    launchDate: "Q4'22",
    priceINR: "₹45,999",
    img_url: "/proccessors/ic-6.jpeg"
  },
  {
    title: "Intel® Core™ Processors",
    name: "Intel® Core™ i7-13700K",
    cores: "16 (8P, 8E)",
    maxTurboFrequencyGHz: "5.4 GHz",
    cacheMB: "30 MB",
    graphics: "Intel® UHD Graphics 770",
    launchDate: "Q4'22",
    priceINR: "₹38,000",
    img_url: "/proccessors/ic-7.jpeg"
  },
  {
    title: "Intel® Core™ Processors",
    name: "Intel® Core™ i5-13600K",
    cores: "14 (6P, 8E)",
    maxTurboFrequencyGHz: "5.1 GHz",
    cacheMB: "24 MB",
    graphics: "Intel® UHD Graphics 770",
    launchDate: "Q4'22",
    priceINR: "₹31,450",
    img_url: "/proccessors/ic-8.jpeg"
  },
  {
    title: "Intel® Core™ Processors",
    name: "Intel® Core™ i3-13100",
    cores: "4P",
    maxTurboFrequencyGHz: "4.5 GHz",
    cacheMB: "12 MB",
    graphics: "Intel® UHD Graphics 730",
    launchDate: "Q1'23",
    priceINR: "₹24,299",
    img_url: "/proccessors/ic-9.jpeg"
  },
  
  {
    title: "Intel® Xeon® Processors",
    name: "Intel® Xeon® 6745P",
    cores: "32",
    baseFrequencyGHz: "3.10 GHz",
    maxTurboFrequencyGHz: "4.30 GHz",
    cacheMB: "336 MB",
    tdpW: "300 W",
    launchDate: "Q1'25",
    priceINR: "₹45,999",
    img_url: "/proccessors/ic-11.jpeg",
  },
  {
    title: "Intel® Xeon® Processors",
    name: "Intel® Xeon® 6728P",
    cores: "24",
    baseFrequencyGHz: "2.70 GHz",
    maxTurboFrequencyGHz: "4.10 GHz",
    graphics: "Intel® Graphics",
    tdpW: "210 W",
    launchDate: "Q1'25",
    priceINR: "₹38,000",
    img_url: "/proccessors/ic-12.jpeg",
  },
  {
    title: "Intel® Xeon® Processors",
    name: "Intel® Xeon® 6517P",
    cores: "16",
    baseFrequencyGHz: "3.20 GHz",
    maxTurboFrequencyGHz: "4.20 GHz",
    cacheMB: "72 MB",
    tdpW: "190 W",
    launchDate: "Q1'25",
    priceINR: "₹31,450",
    img_url: "/proccessors/ic-13.jpeg",
  },
  {
    title: "Intel® Xeon® Processors",
    name: "Intel® Xeon® 6511P",
    cores: "16",
    baseFrequencyGHz: "2.30 GHz",
    maxTurboFrequencyGHz: "4.20 GHz",
    cacheMB: "72 MB",
    tdpW: "150 W",
    launchDate: "Q1'25",
    priceINR: "₹24,299",
    img_url: "/proccessors/ic-14.jpeg",
  },
  
  {
    title: "Intel® Xeon® CPU Max Series",
    name: "Intel® Xeon® CPU Max 9462",
    cores: "32",
    baseFrequencyGHz: "2.70 GHz",
    maxTurboFrequencyGHz: "3.50 GHz",
    cacheMB: "75 MB",
    tdpW: "350 W",
    launchDate: "Q1'23",
    priceINR: "₹45,999",
    img_url: "/proccessors/ic-16.jpeg",
  },
  {
    title: "Intel® Xeon® CPU Max Series",
    name: "Intel® Xeon® CPU Max 9480",
    cores: "56",
    baseFrequencyGHz: "1.90 GHz",
    maxTurboFrequencyGHz: "3.50 GHz",
    cacheMB: "112.5 MB",
    tdpW: "350 W",
    launchDate: "Q1'23",
    priceINR: "₹38,000",
    img_url: "/proccessors/ic-17.jpeg",
  },
  {
    title: "Intel® Xeon® CPU Max Series",
    name: "Intel® Xeon® CPU Max 9470",
    cores: "52",
    baseFrequencyGHz: "2.00 GHz",
    maxTurboFrequencyGHz: "3.50 GHz",
    cacheMB: "105 MB",
    tdpW: "350 W",
    launchDate: "Q1'23",
    priceINR: "₹31,450",
    img_url: "/proccessors/ic-18.jpeg",
  },  
];

module.exports = {data : Proccessordata}
