const Systemdata = [
    {
  title: "AI PCs Powered by Intel",
  name: "Acer Swift Neo AI Laptop",
  proccessor: "Intel Core Ultra",
  graphics: "Intel Arc",
  Display: '14" WUXGA IPS',
  priceINR: "₹74,999",
  img_url: "./Systems/s-1.jpeg",
  weight: "1.2 kg",
  Design: "Aluminium chassis with Rose Gold finish"
},
{
  title: "AI PCs Powered by Intel",
  name: "HP OmniStudio X All-in-One PC",
  proccessor: "Intel Core Ultra",
  graphics: "Intel Arc",
  Display: '32" 4K',
  priceINR: "₹68,000",
    img_url: "./Systems/s-2.jpeg",
},
{
  title: "AI PCs Powered by Intel",
  name: "HP 2024 ZBook Firefly G11 Mobile Workstation",
  proccessor: "Intel Core Ultra 7",
  graphics: "Integrated",
  Display: '16" WUXGA IPS',
  Memory: "16GB RAM",
  Storage: "512GB SSD",
  priceINR: "₹1,41,499",
  img_url: "./Systems/s-3.jpeg",
},
{
  title: "AI PCs Powered by Intel",
  name: "Acer Swift Go AI SFG14-72T",
  proccessor: "Intel® Core™ Ultra 7 155H",
  graphics: "Intel Arc Graphics",
  Display: '14" TFT LCD',
  Memory: "16GB RAM",
  Storage: "1TB SSD",
  priceINR: "₹85,990",
  img_url: "./Systems/s-4.jpeg",
},
{
  title: "Gaming Systems (Intel Inside)",
  name: "HP OMEN MAX 16 (2025)",
  proccessor: "Intel® Core™ Ultra 9",
  graphics: "NVIDIA RTX 50-series",
  Display: '16" OLED QHD+',
  Memory: "Up to 64GB RAM",
  Storage: "Varies",
  priceINR: "Starting at $2,499.99",
  img_url: "./Systems/s-5.jpeg",
},
{
  title: "Gaming Systems (Intel Inside)",
  name: "MSI Raider 18 HX AI",
  proccessor: "Intel® Core™ Ultra",
  graphics: "NVIDIA RTX 5080",
  Display: '18" Mini-LED',
  Memory: "Varies",
  Storage: "Varies",
  priceINR: "$78,999",
  img_url: "./Systems/s-6.jpeg",
},
{
  title: "Gaming Systems (Intel Inside)",
  name: "MSI Stealth 16 AI Studio",
  proccessor: "Intel® Core™ Ultra 9 185H",
  graphics: "NVIDIA GeForce RTX 4080",
  Display: '16" UHD+ Mini LED',
  Memory: "64GB DDR5",
  Storage: "1TB SSD",
  priceINR: "₹2,69,990",
  img_url: "./Systems/s-7.jpeg",
},
{
  title: "Gaming Systems (Intel Inside)",
  name: "Lenovo Legion Pro 5 Gen 10",
  proccessor: "Intel® Core™ i9",
  graphics: "NVIDIA RTX 5060",
  Display: '15.6"',
  Memory: "Varies",
  Storage: "Varies",
  priceINR: "₹1,76,500",
  img_url: "./Systems/s-8.jpeg",
}

];

module.exports = {data : Systemdata}